steps:
  # Build frontend
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']
    dir: 'frontend'
    id: 'install-frontend-deps'

  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'frontend'
    env:
      - 'VITE_API_URL=/api'
      - 'NODE_ENV=production'
    id: 'build-frontend'
    waitFor: ['install-frontend-deps']

  # Run backend tests
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        python -m pytest tests/ || true
    id: 'test-backend'

  # Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud app deploy app.yaml \
          --project=$PROJECT_ID \
          --quiet \
          --promote \
          --stop-previous-version
    id: 'deploy-app'
    waitFor: ['build-frontend', 'test-backend']

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'