version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: toluai-postgres-dev
    environment:
      POSTGRES_DB: toluai_dev
      POSTGRES_USER: toluai_dev
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-toluai_dev_pass123}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./scripts/init_extensions.sql:/docker-entrypoint-initdb.d/00_extensions.sql
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U toluai_dev -d toluai_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - toluai-dev-network

  redis:
    image: redis:7-alpine
    container_name: toluai-redis-dev
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis_dev_pass123}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - toluai-dev-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: toluai-pgadmin-dev
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@toluai.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_dev_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - toluai-dev-network

volumes:
  postgres_dev_data:
  redis_dev_data:
  pgadmin_dev_data:

networks:
  toluai-dev-network:
    driver: bridge